# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
env:
  - NUMPY_VER=1.7.0
before_install:
  - mkdir builds
  - pushd builds
  - pip install -q http://switch.dl.sourceforge.net/project/numpy/NumPy/${NUMPY_VER}/numpy-${NUMPY_VER}.tar.gz
  - sudo apt-get install libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - pip install scipy
  # pandas 0.14.0 blows up on python 2.6:
  #   https://github.com/pydata/pandas/issues/7284
  - pip install pandas==0.13.1
  - pip install coverage
  - popd
  - python -V
  - which nosetests
  - python -c 'import numpy; print(numpy.__version__)'
install:
  - python setup.py sdist
  - pip install dist/*
script:
  # We change directories to make sure that python won't find the copy
  # of patsy in the source directory.
  - mkdir empty
  - cd empty
  - INSTALLDIR=$(python -c "import os; import patsy; print(os.path.dirname(patsy.__file__))")
  - export PYTHONWARNINGS=default PATSY_FORCE_NO_WARNINGS=1
  # The --exe is because python sometimes marks all installed modules
  # as executable, so without --exe nosetests will just ignore
  # everything. Baffling, but so it goes.
  - coverage run --source=$INSTALLDIR --rcfile=../.coveragerc $(which nosetests) --exe --failure-detail --all-modules $INSTALLDIR
  - coverage report --rcfile=../.coveragerc --show-missing
  - python ../tools/check-API-refs.py
notifications:
  email:
    - njs@pobox.com
after_success:
  - pip install coveralls && coveralls
